class SignupData {
  static const List<String> arabicCountries = [
    'Algeria',
    'Bahrain',
    'Comoros',
    'Djibouti',
    'Egypt',
    'Iraq',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Libya',
    'Mauritania',
    'Morocco',
    'Oman',
    'Palestine',
    'Qatar',
    'Saudi Arabia',
    'Somalia',
    'Sudan',
    'Syria',
    'Tunisia',
    'UAE',
    'Yemen',
  ];

  static const List<String> supportedCountries = [
    ...arabicCountries,
    'Afghanistan',
    'Albania',
    'Argentina',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bangladesh',
    'Belgium',
    'Benin',
    'Bosnia and Herzegovina',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Congo',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Dominican Republic',
    'Ecuador',
    'Ethiopia',
    'Finland',
    'France',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Guinea',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Ireland',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Kazakhstan',
    'Kenya',
    'Kosovo',
    'Kyrgyzstan',
    'Latvia',
    'Liberia',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Mexico',
    'Moldova',
    'Montenegro',
    'Mozambique',
    'Myanmar',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Niger',
    'Nigeria',
    'Norway',
    'Pakistan',
    'Panama',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'Rwanda',
    'Senegal',
    'Serbia',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'South Korea',
    'Spain',
    'Sri Lanka',
    'Sweden',
    'Switzerland',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Trinidad and Tobago',
    'Turkey',
    'Turkmenistan',
    'Uganda',
    'Ukraine',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Zambia',
    'Zimbabwe',
  ];

  static const Map<String, List<String>> countryCities = {
    'Algeria': [
      'Algiers',
      'Oran',
      'Constantine',
      'Annaba',
      'Blida',
      'Batna',
      'Djelfa',
      'Setif',
      'Sidi Bel Abbès',
      'Biskra',
    ],
    'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Aali'],
    'Comoros': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Mirontsi'],
    'Djibouti': ['Djibouti City', 'Ali Sabieh', 'Tadjoura', 'Obock', 'Dikhil'],
    'Egypt': [
      'Cairo',
      'Alexandria',
      'Giza',
      'Shubra El Kheima',
      'Port Said',
      'Suez',
      'Luxor',
      'Mansoura',
      'Tanta',
      'Asyut',
    ],
    'Iraq': [
      'Baghdad',
      'Basra',
      'Mosul',
      'Erbil',
      'Abu Ghraib',
      'Sulaymaniyah',
      'Kirkuk',
      'Najaf',
      'Karbala',
      'Nasiriyah',
    ],
    'Jordan': [
      'Amman',
      'Zarqa',
      'Irbid',
      'Russeifa',
      'Sahab',
      'Aqaba',
      'Madaba',
      'Salt',
    ],
    'Kuwait': [
      'Kuwait City',
      'Al Ahmadi',
      'Hawalli',
      'Salmiya',
      'Sabah Al Salem',
    ],
    'Lebanon': [
      'Beirut',
      'Tripoli',
      'Sidon',
      'Tyre',
      'Nabatieh',
      'Jounieh',
      'Zahlé',
      'Baabda',
    ],
    'Libya': [
      'Tripoli',
      'Benghazi',
      'Misrata',
      'Bayda',
      'Zawiya',
      'Zliten',
      'Tobruk',
      'Sabha',
    ],
    'Mauritania': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Adel Bagrou', 'Boghé'],
    'Morocco': [
      'Casablanca',
      'Rabat',
      'Fes',
      'Marrakech',
      'Tangier',
      'Agadir',
      'Meknes',
      'Oujda',
      'Kenitra',
      'Tetouan',
    ],
    'Oman': [
      'Muscat',
      'Salalah',
      'Seeb',
      'Sohar',
      'Nizwa',
      'Khasab',
      'Sur',
      'Ibri',
    ],
    'Palestine': [
      'East Jerusalem',
      'Gaza City',
      'Hebron',
      'Nablus',
      'Khan Yunis',
      'Jabalya',
      'Rafah',
      'Tulkarm',
      'Qalqilya',
      'Ramallah',
    ],
    'Qatar': [
      'Doha',
      'Al Rayyan',
      'Al Wakrah',
      'Al Khor',
      'Umm Salal Muhammad',
    ],
    'Saudi Arabia': [
      'Riyadh',
      'Jeddah',
      'Mecca',
      'Medina',
      'Sultanah',
      'Dammam',
      'Taif',
      'Tabuk',
      'Al Kharj',
      'Buraidah',
    ],
    'Somalia': ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo', 'Baidoa'],
    'Sudan': ['Khartoum', 'Omdurman', 'Khartoum North', 'Nyala', 'Port Sudan'],
    'Syria': [
      'Damascus',
      'Aleppo',
      'Homs',
      'Hama',
      'Latakia',
      'Deir ez-Zor',
      'Raqqa',
      'Al-Hasakah',
      'Tartus',
      'Idlib',
    ],
    'Tunisia': [
      'Tunis',
      'Sfax',
      'Sousse',
      'Ettadhamen-Mnihla',
      'Kairouan',
      'Bizerte',
      'Gabès',
      'Ariana',
      'Gafsa',
      'La Marsa',
    ],
    'UAE': [
      'Abu Dhabi',
      'Dubai',
      'Sharjah',
      'Al Ain',
      'Ajman',
      'Ras Al Khaimah',
      'Fujairah',
      'Umm Al Quwain',
    ],
    'United Arab Emirates': [
      'Abu Dhabi',
      'Dubai',
      'Sharjah',
      'Al Ain',
      'Ajman',
      'Ras Al Khaimah',
      'Fujairah',
      'Umm Al Quwain',
    ],
    'Yemen': [
      'Sana\'a',
      'Aden',
      'Taiz',
      'Al Hudaydah',
      'Ibb',
      'Dhamar',
      'Mukalla',
      'Zinjibar',
    ],
    'Afghanistan': [
      'Kabul',
      'Herat',
      'Mazar-i-Sharif',
      'Kandahar',
      'Jalalabad',
      'Kunduz',
    ],
    'Argentina': [
      'Buenos Aires',
      'Cordoba',
      'Rosario',
      'Mendoza',
      'La Plata',
      'Mar del Plata',
    ],
    'Australia': [
      'Sydney',
      'Melbourne',
      'Brisbane',
      'Perth',
      'Adelaide',
      'Canberra',
    ],
    'Bangladesh': [
      'Dhaka',
      'Chittagong',
      'Khulna',
      'Rajshahi',
      'Sylhet',
      'Barisal',
    ],
    'Bosnia and Herzegovina': [
      'Sarajevo',
      'Banja Luka',
      'Tuzla',
      'Zenica',
      'Mostar',
      'Bijeljina',
    ],
    'Brazil': [
      'Sao Paulo',
      'Rio de Janeiro',
      'Brasilia',
      'Salvador',
      'Fortaleza',
      'Belo Horizonte',
    ],
    'Canada': [
      'Toronto',
      'Montreal',
      'Vancouver',
      'Calgary',
      'Ottawa',
      'Edmonton',
    ],
    'China': [
      'Beijing',
      'Shanghai',
      'Guangzhou',
      'Shenzhen',
      'Chengdu',
      'Hangzhou',
    ],
    'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Lille'],
    'Germany': [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
    ],
    'India': [
      'Mumbai',
      'Delhi',
      'Bengaluru',
      'Hyderabad',
      'Chennai',
      'Kolkata',
    ],
    'Indonesia': [
      'Jakarta',
      'Surabaya',
      'Bandung',
      'Medan',
      'Semarang',
      'Makassar',
    ],
    'Iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz'],
    'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Bologna'],
    'Japan': ['Tokyo', 'Osaka', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka'],
    'Kazakhstan': [
      'Almaty',
      'Astana',
      'Shymkent',
      'Aktobe',
      'Karaganda',
      'Atyrau',
    ],
    'Malaysia': [
      'Kuala Lumpur',
      'George Town',
      'Johor Bahru',
      'Ipoh',
      'Kota Kinabalu',
      'Shah Alam',
    ],
    'Maldives': [
      'Male',
      'Addu City',
      'Fuvahmulah',
      'Kulhudhuffushi',
      'Thinadhoo',
      'Naifaru',
    ],
    'Mexico': [
      'Mexico City',
      'Guadalajara',
      'Monterrey',
      'Puebla',
      'Tijuana',
      'Merida',
    ],
    'Netherlands': [
      'Amsterdam',
      'Rotterdam',
      'The Hague',
      'Utrecht',
      'Eindhoven',
      'Groningen',
    ],
    'New Zealand': [
      'Auckland',
      'Wellington',
      'Christchurch',
      'Hamilton',
      'Dunedin',
      'Tauranga',
    ],
    'Nigeria': ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Kaduna'],
    'Pakistan': [
      'Karachi',
      'Lahore',
      'Islamabad',
      'Rawalpindi',
      'Faisalabad',
      'Peshawar',
    ],
    'Russia': [
      'Moscow',
      'Saint Petersburg',
      'Novosibirsk',
      'Yekaterinburg',
      'Kazan',
      'Sochi',
    ],
    'Senegal': [
      'Dakar',
      'Touba',
      'Thies',
      'Saint-Louis',
      'Kaolack',
      'Ziguinchor',
    ],
    'Singapore': ['Singapore'],
    'South Africa': [
      'Johannesburg',
      'Cape Town',
      'Durban',
      'Pretoria',
      'Port Elizabeth',
      'Bloemfontein',
    ],
    'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju'],
    'Spain': [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Seville',
      'Zaragoza',
      'Malaga',
    ],
    'Sri Lanka': [
      'Colombo',
      'Kandy',
      'Galle',
      'Jaffna',
      'Negombo',
      'Trincomalee',
    ],
    'Sweden': [
      'Stockholm',
      'Gothenburg',
      'Malmo',
      'Uppsala',
      'Vasteras',
      'Orebro',
    ],
    'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Lucerne'],
    'Tanzania': [
      'Dar es Salaam',
      'Dodoma',
      'Arusha',
      'Mwanza',
      'Zanzibar City',
      'Mbeya',
    ],
    'Thailand': [
      'Bangkok',
      'Chiang Mai',
      'Phuket',
      'Pattaya',
      'Khon Kaen',
      'Hat Yai',
    ],
    'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Konya'],
    'United Kingdom': [
      'London',
      'Birmingham',
      'Manchester',
      'Glasgow',
      'Liverpool',
      'Leeds',
    ],
    'United States': [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Miami',
      'San Francisco',
    ],
    'Uzbekistan': [
      'Tashkent',
      'Samarkand',
      'Bukhara',
      'Namangan',
      'Andijan',
      'Nukus',
    ],
  };

  static const List<String> genders = ['Male', 'Female'];
  static const List<String> maritalStatuses = [
    'Never Married',
    'Married',
    'Divorced',
    'Widowed',
  ];
  static const List<String> sects = [
    'Sunni',
    'Shia',
    'Sufi',
    'Other',
    'Prefer not to say',
  ];
  static const List<String> religiousLevels = [
    'Very Practicing',
    'Practicing',
    'Moderate',
    'Liberal',
  ];
  static const List<String> prayerFrequencies = [
    'Actively Practicing',
    'Occasionally',
    'Not Practicing',
  ];
  static const List<String> educationLevels = [
    'High School',
    'Bachelors',
    'Masters',
    'Doctorate',
    'Islamic Studies',
    'Other',
  ];

  static const List<String> dietaryPreferences = ['Halal', 'Non strict'];
  static const List<String> alcoholPreferences = ['Doesnt drink', 'Drinks'];
  static const List<String> hijabStatuses = ['Covered', 'Niqab', 'Not covered'];
  static const List<String> childrenOptions = [
    "Doesn't have children",
    'Has children',
  ];

  static const List<String> languagesList = [
    'Arabic',
    'English',
    'French',
    'Urdu',
    'Turkish',
    'Persian',
    'Bengali',
    'Malay',
    'Indonesian',
    'Spanish',
  ];

  static const List<String> ethnicities = [
    'Afghan',
    'African / Afro-descendant',
    'Arab',
    'Azerbaijani',
    'Bangladeshi',
    'Caribbean',
    'Kurdish',
    'Malay',
    'Pakistani',
    'Persian',
    'Somali',
    'South Asian',
    'Turkish',
    'Other',
  ];

  static const List<String> familyValuesOptions = [
    'Strong believer of family bonds',
    'Desires children',
    'Shared household responsibilities',
    'Close to parents',
    'Faith-centered home',
    'Long-term commitment',
  ];

  static const List<String> hobbiesList = [
    'Reading',
    'Travel',
    'Cooking',
    'Sports',
    'Photography',
    'Music',
    'Art',
    'Gaming',
    'Fitness',
    'Nature',
    'Volunteering',
    'Writing',
    'Fashion',
    'Technology',
    'Movies',
    'Hiking',
    'Swimming',
    'Cycling',
    'Yoga',
    'Meditation',
    'Dancing',
    'Coffee',
    'Shopping',
    'Camping',
    'Fishing',
  ];

  static const List<String> communicationStylesList = [
    'direct',
    'gentle',
    'humorous',
    'reserved',
    'expressive',
  ];
}
