class SignupData {
  static const List<String> arabicCountries = [
    'Algeria',
    'Bahrain',
    'Comoros',
    'Djibouti',
    'Egypt',
    'Iraq',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Libya',
    'Mauritania',
    'Morocco',
    'Oman',
    'Palestine',
    'Qatar',
    'Saudi Arabia',
    'Somalia',
    'Sudan',
    'Syria',
    'Tunisia',
    'UAE',
    'Yemen',
  ];

  static const Map<String, List<String>> countryCities = {
    'Algeria': [
      'Algiers',
      'Oran',
      'Constantine',
      'Annaba',
      'Blida',
      'Batna',
      'Djelfa',
      'Sétif',
      'Sidi Bel Abbès',
      'Biskra',
    ],
    'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Aali'],
    'Comoros': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Mirontsi'],
    'Djibouti': ['Djibouti City', 'Ali Sabieh', 'Tadjoura', 'Obock', 'Dikhil'],
    'Egypt': [
      'Cairo',
      'Alexandria',
      'Giza',
      'Shubra El Kheima',
      'Port Said',
      'Suez',
      'Luxor',
      'Mansoura',
      'Tanta',
      'Asyut',
    ],
    'Iraq': [
      'Baghdad',
      'Basra',
      'Mosul',
      'Erbil',
      'Abu Ghraib',
      'Sulaymaniyah',
      'Kirkuk',
      'Najaf',
      'Karbala',
      'Nasiriyah',
    ],
    'Jordan': [
      'Amman',
      'Zarqa',
      'Irbid',
      'Russeifa',
      'Sahab',
      'Aqaba',
      'Madaba',
      'Salt',
    ],
    'Kuwait': [
      'Kuwait City',
      'Al Ahmadi',
      'Hawalli',
      'Salmiya',
      'Sabah Al Salem',
    ],
    'Lebanon': [
      'Beirut',
      'Tripoli',
      'Sidon',
      'Tyre',
      'Nabatieh',
      'Jounieh',
      'Zahlé',
      'Baabda',
    ],
    'Libya': [
      'Tripoli',
      'Benghazi',
      'Misrata',
      'Bayda',
      'Zawiya',
      'Zliten',
      'Tobruk',
      'Sabha',
    ],
    'Mauritania': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Adel Bagrou', 'Boghé'],
    'Morocco': [
      'Casablanca',
      'Rabat',
      'Fes',
      'Marrakech',
      'Tangier',
      'Agadir',
      'Meknes',
      'Oujda',
      'Kenitra',
      'Tetouan',
    ],
    'Oman': [
      'Muscat',
      'Salalah',
      'Seeb',
      'Sohar',
      'Nizwa',
      'Khasab',
      'Sur',
      'Ibri',
    ],
    'Palestine': [
      'East Jerusalem',
      'Gaza City',
      'Hebron',
      'Nablus',
      'Khan Yunis',
      'Jabalya',
      'Rafah',
      'Tulkarm',
      'Qalqilya',
      'Ramallah',
    ],
    'Qatar': [
      'Doha',
      'Al Rayyan',
      'Al Wakrah',
      'Al Khor',
      'Umm Salal Muhammad',
    ],
    'Saudi Arabia': [
      'Riyadh',
      'Jeddah',
      'Mecca',
      'Medina',
      'Sultanah',
      'Dammam',
      'Taif',
      'Tabuk',
      'Al Kharj',
      'Buraidah',
    ],
    'Somalia': ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo', 'Baidoa'],
    'Sudan': ['Khartoum', 'Omdurman', 'Khartoum North', 'Nyala', 'Port Sudan'],
    'Syria': [
      'Damascus',
      'Aleppo',
      'Homs',
      'Hama',
      'Latakia',
      'Deir ez-Zor',
      'Raqqa',
      'Al-Hasakah',
      'Tartus',
      'Idlib',
    ],
    'Tunisia': [
      'Tunis',
      'Sfax',
      'Sousse',
      'Ettadhamen-Mnihla',
      'Kairouan',
      'Bizerte',
      'Gabès',
      'Ariana',
      'Gafsa',
      'La Marsa',
    ],
    'UAE': [
      'Abu Dhabi',
      'Dubai',
      'Sharjah',
      'Al Ain',
      'Ajman',
      'Ras Al Khaimah',
      'Fujairah',
      'Umm Al Quwain',
    ],
    'Yemen': [
      'Sana\'a',
      'Aden',
      'Taiz',
      'Al Hudaydah',
      'Ibb',
      'Dhamar',
      'Mukalla',
      'Zinjibar',
    ],
  };

  static const List<String> genders = ['Male', 'Female'];
  static const List<String> maritalStatuses = [
    'Never Married',
    'Married',
    'Divorced',
    'Widowed',
  ];
  static const List<String> sects = [
    'Sunni',
    'Shia',
    'Sufi',
    'Other',
    'Prefer not to say',
  ];
  static const List<String> religiousLevels = [
    'Very Practicing',
    'Practicing',
    'Moderate',
    'Liberal',
  ];
  static const List<String> prayerFrequencies = [
    'Actively Practicing',
    'Occasionally',
    'Not Practicing',
  ];
  static const List<String> educationLevels = [
    'High School',
    'Bachelors',
    'Masters',
    'Doctorate',
    'Islamic Studies',
    'Other',
  ];

  static const List<String> dietaryPreferences = ['Halal', 'Non strict'];
  static const List<String> alcoholPreferences = ['Doesnt drink', 'Drinks'];
  static const List<String> hijabStatuses = ['Covered', 'Niqab', 'Not covered'];
  static const List<String> childrenOptions = [
    "Doesn't have children",
    'Has children',
  ];

  static const List<String> languagesList = [
    'Arabic',
    'English',
    'French',
    'Urdu',
    'Turkish',
    'Persian',
    'Bengali',
    'Malay',
    'Indonesian',
    'Spanish',
  ];

  static const List<String> ethnicities = [
    'Afghan',
    'African American',
    'Arab',
    'Azeri',
    'Bangladeshi',
    'Caribbean',
    'Desi',
    'Kurdish',
    'Malay',
    'Pakistani',
    'Persian',
    'Somali',
    'Turkish',
    'Other',
  ];

  static const List<String> familyValuesOptions = [
    'Strong believer of family bonds',
    'Desires children',
    'Shared household responsibilities',
    'Close to parents',
    'Faith-centered home',
    'Long-term commitment',
  ];

  static const List<String> hobbiesList = [
    'Reading',
    'Travel',
    'Cooking',
    'Sports',
    'Photography',
    'Music',
    'Art',
    'Gaming',
    'Fitness',
    'Nature',
    'Volunteering',
    'Writing',
    'Fashion',
    'Technology',
    'Movies',
    'Hiking',
    'Swimming',
    'Cycling',
    'Yoga',
    'Meditation',
    'Dancing',
    'Coffee',
    'Shopping',
    'Camping',
    'Fishing',
  ];
}
