platform :ios, '15.5'

use_modular_headers!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def patch_permission_handler_service_status_file(file)
  return unless File.file?(file)
  return unless ['.h', '.m', '.mm'].include?(File.extname(file))

  contents = File.read(file)
  patched_contents = contents.gsub(/\benum ServiceStatus\b/, 'PermissionHandlerServiceStatus').gsub(/\bServiceStatus\b/, 'PermissionHandlerServiceStatus')
  File.write(file, patched_contents) if patched_contents != contents
end

def patch_permission_handler_service_status(installer = nil)
  permission_handler_paths = [
    File.join(__dir__, 'Pods', '.symlinks', 'plugins', 'permission_handler_apple', 'ios', 'Classes'),
    File.join(__dir__, 'Pods', 'Headers', 'Public', 'permission_handler_apple'),
    File.join(__dir__, 'Pods', 'Headers', 'Private', 'permission_handler_apple')
  ]

  resolved_paths = permission_handler_paths.flat_map do |permission_handler_path|
    next [] unless Dir.exist?(permission_handler_path)

    begin
      [permission_handler_path, File.realpath(permission_handler_path)]
    rescue Errno::ENOENT
      [permission_handler_path]
    end
  end.uniq

  resolved_paths.each do |permission_handler_path|
    Dir.glob(File.join(permission_handler_path, '**', '*.{h,m,mm}')).each do |file|
      patch_permission_handler_service_status_file(file)
    end
  end

  return unless installer

  installer.pods_project.targets.each do |target|
    next unless target.name == 'permission_handler_apple'
    next unless target.respond_to?(:source_build_phase) && target.source_build_phase

    target.source_build_phase.files_references.each do |file_ref|
      begin
        patch_permission_handler_service_status_file(file_ref.real_path.to_s)
      rescue StandardError
        next
      end
    end
  end
end

pre_install do |_installer|
  patch_permission_handler_service_status
end

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  patch_permission_handler_service_status(installer)

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
